---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

This is a practice package for [STAT 545](http://stat545-ubc.github.io).

This has been extended by Yucheng Zhang to include two more functions (ffactor and freorder). First created by Jenny as a posting for students to consult / start with for their homework.

Here's how to use the `foofactors` package.
```{r}
library(devtools)
#install_github("y252zhan/foofactors")
library(foofactors)
#functions created by Jenny
fbind(iris$Species[c(1, 51, 101)], PlantGrowth$group[c(1, 11, 21)])
freq_out(iris$Species)
#functions extended by Yucheng Zhang
# ffactor is a version of factor() that sets levels to the order in which they appear in the data
ffactor(c("C", "D", "B", "A"))
# freorder is a version of reorder() that reorder levels in descending order according to the numeric value of the second argument
freorder(school <- c("School A", "SChool B", "School C", "School D", "School E", "School F"), N <- c(25,28,12,22,30,25))
```

